routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@welcome')->name('welcome');   


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/ciudades/search', 'CiudadesController@search')->name('ciudades.search');

Route::resource('/comercio','ComercioController');
Route::resource('/usuario','UserController');
Route::resource('/usuario/preferencias','PreferenciasUsuarioController');
Route::resource('/producto','ProductosController');
Route::resource('/categoria','CategoriasController');
Route::resource('/marca','MarcasController');

Route::post('/getAllProducts','ProductosController@getAllProducts')->name('getAllProducts');
Route::post('/getAllCategories','CategoriasController@getAllCategories')->name('getAllCategories');
Route::post('/getAllMarcas','MarcasController@getAllMarcas')->name('getAllMarcas');

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\UnidadMedida;
use App\Categoria;
use App\Marca;

class Producto extends Model
{
    protected $fillable = [
        'id_unidad_medida','id_categoria' ,'id_marca', 'cod_manual', 'cod_bar', 'descripcion', 'descripcion_completa', 'producto_servicio', 'tipo_iva','nombre_imagen','activo', 
    ];


    public function unidad_medida(){
        return $this->belongsTo(UnidadMedida::class,'id_unidad_medida','id');
    }
    
    public function categoria(){
        return $this->belongsTo(Categoria::class,'id_categoria','id');
    }
    public function marca(){
        return $this->belongsTo(Marca::class,'id_marca','id');
    }
    
}

app/Http/Controllers/ProductosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use Auth;
use App\Producto;
use App\UnidadMedida;
use App\Marca;
use App\Categoria;
use App\Comercio;

class ProductosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $productos = Producto::get('*');
        $admin_comercio = Comercio::find(Auth::user()->comercio->id);
        $umedidas = UnidadMedida::get('*');
        $marcas = Marca::get('*');
        $categorias = Categoria::get('*');
        $admin_comercio = Comercio::find(Auth::user()->comercio->id);
        return view('productos/index',['productos' => $productos,'umedidas' => $umedidas,'marcas' => $marcas,'categorias' => $categorias,'admin_comercio' =>$admin_comercio]);
    }

    public function getAllProducts(){
        $productos = Producto::get('*');
        $html = "";
        foreach($productos as $p){
            $html .= '<tr id="t-body tb'.$p->id.'">
                        <th scope="row">'.$p->cod_bar.'</th>
                        <th scope="row">'.$p->descripcion.'</th>
                        <td>'.$p->categoria->categoria.'</td>
                        <td>'.$p->unidad_medida->unidad_medida.'</td>
                        <td>'.$p->tipo_iva.'</td>
                        <td>'.$p->activo.'</td>';
            $html .= '<td>
            <div class="btn-group">
                <a class="btn btn-sm btn-primary" href="{{route(\'producto.show\','.$p->id.')}}" tooltip="Ver más detalles">
                    <span class="fa fa-eye"></span>
                </a>
                <a class="btn btn-sm btn-secondary " href="{{route(\'producto.edit\','.$p->id.')}}" tooltip="Modificar registro">
                    <span class="fa fa-edit"></span>
                </a>
                <form id="#destroy'.$p->id.'" method="POST" action="{{route(\'producto.destroy\','.$p->id.')}}">

                    <meta name="csrf-token" content="{{ csrf_token() }}">
                    
                </form>
                <a data-id="'.$p->id.'" class="btn btn-sm btn-danger delete_product" tooltip="Eliminar registro"
                        onclick="var id = $(this).data(\'id\'); deleteProduct(id);">
                        <span id="delete'.$p->id.'" class="fa fa-trash"></span>
                    </a>
        
            </div>
        </td>';
        }
        return response()->json([
            'html' => $html
        ]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $umedidas = UnidadMedida::get('*');
        $marcas = Marca::get('*');
        $categorias = Categoria::get('*');
        $admin_comercio = Comercio::find(Auth::user()->comercio->id);
        return view('productos/create',['umedidas' => $umedidas,'marcas' => $marcas,'categorias' => $categorias,'admin_comercio' =>$admin_comercio]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $producto = new Producto($request->all());
           
        $producto->nombre_imagen = "vacio";
        $producto->save();
        
        if($request->file('image') != null ){  
             $producto->nombre_imagen = $producto->id.'__'.$request->file('image')->getClientOriginalName();
             $path = $request->file('image')->storeAs('public/images',$producto->id.'__'.$request->file('image')->getClientOriginalName());
         }  
         
        $producto->save();

        return redirect('/producto')->with('success', '¡El producto se registró satisfactoriamente!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $producto = Producto::find($id);
        $umedidas = UnidadMedida::get('*');
        $marcas = Marca::get('*');
        $categorias = Categoria::get('*');
        $admin_comercio = Comercio::find(Auth::user()->comercio->id);
        $image = Storage::url('public/images/'.$producto->nombre_imagen);
        return view('productos/edit',['imagen'=>$image,'producto' => $producto,'umedidas' => $umedidas,'marcas' => $marcas,'categorias' => $categorias,'admin_comercio' =>$admin_comercio]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $producto = Producto::find($id);
        $file = $producto->id.'__'.$request->file('image')->getClientOriginalName();
        if($request->file('image') != null ){
            Storage::delete(['public/images/'.$producto->nombre_imagen]);
            $producto->nombre_imagen = $file;
            $path = $request->file('image')->storeAs('public/images',$file);
        }
        $producto->update($request->all());
        return redirect('producto');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Producto::find($id)->delete($id);
        return response()->json([
            'success' => 'Registro eliminado con éxito.'
        ]);
    }
}

resources/views/productos/create.blade.php
@extends('layouts.app')

@section('content')
    
    <div class="container bg-info text-center shadow form-inline" style="padding: 10px;">
        <h1 class="text-center col-12">Administración de Productos</h1>
    </div>

    <div class="container pt-4 pb-4 bg-light shadow">
        <div class="card card-light text-dark">
            <h4 class="card-header titulo">
                <a class="btn btn-md btn-primary" href="{{route('producto.index')}}" ><span class="fa fa-arrow-left"></span></a>
                Registrar nuevo producto
            </h4>
            <form action="{{route('producto.store')}}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="card-body">
                <div class="container">
                   
                        <div class="row">
                            <div class="form-group col">
                                <label for="umedida">Unidad de medida</label>
                                <select name="id_unidad_medida" id="unidad_medida" class="form-control">
                                    <option id="new_um">--AGREGAR NUEVO--</option>
                                    @foreach ($umedidas as $um)
                                    <option value="{{$um->id}}" @if ($um->unidad_medida == 'Unidad') selected @endif>{{$um->unidad_medida}}</option>
                                    @endforeach
                                </select>
                            </div>
                                
                            <div class="form-group col">
                                <label for="marca">Marca</label>
                                    <select name="id_marca" id="marca" class="form-control">
                                    <option id="new_marca">--AGREGAR NUEVO--</option>
                                    @foreach ($marcas as $m)
                                        <option value="{{$m->id}}" selected>{{$m->marca}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                                
                        <div class="form-group">
                            <label for="marca">Descripcion corta</label>
                            <textarea name="descripcion" class="form-control" rows="3" maxlength="200"></textarea>
                        </div>
            
                        <div class="form-group">
                            <label for="marca">Descripcion completa</label>
                            <textarea name="descripcion_completa" class="form-control" rows="3" maxlength="500"></textarea>
                        </div>
            
                        <div class="row">
                            <div class="form-group col">
                                <label for="cod_manual">Código manual</label>
                                <input type="text" name="cod_manual" id="cod_manual" class="form-control">
                            </div>
                            
                            <div class="form-group col">
                                <label for="cod_bar">Código barras</label>
                                <input type="text" name="cod_bar" id="cod_bar" class="form-control">
                            </div>
                        </div>
            
                        <div class="row">
                            <div class="form-group col">
                                <label for="producto_servicio">Producto/Servicio</label>
                                <select class="form-control" name="producto_servicio">
                                    <option value="0" selected>Producto</option>
                                    <option value="1">Servicio</option>
                                </select>
                            </div>
                            <div class="form-group col">
                                <label for="marca">Categoría</label>
                                <div class="input-group">
                                    <select name="id_categoria" id="marca" class="form-control">
                                            @foreach ($categorias as $c)
                                                <option value="{{$c->id}}">{{$c->categoria}}</option>
                                            @endforeach
                                    </select>
                                    <input type="text" class="form-control" id="cat_name">
                                    <div class="input-group-prepend">
                                            <a class="btn btn-md btn-outline-primary" id="#addC" href="#" onclick="saveCategory()">
                                                <span class="fa fa-plus-circle"></span>
                                            </a>
                                    </div>
                                </div>
                                
                            </div>

                            <div class="form-group col">
                                <label for="tipo_iva">Tipo I.V.A.</label>
                                <select class="form-control" name="tipo_iva">
                                    <option value="10" selected>10%</option>
                                    <option value="5" >5%</option>
                                    <option value="excenta" >EXCENTA</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <input name="activo" type="checkbox" aria-label="Activar/Desactiva producto">
                                    </div>
                                    <input type='text' class="form-control" readonly disabled value="Activar/Desactiva producto">
                            </div>
                            </div>
                            <div class="form-group">
                                <label>Logotipo</label>
                                <input name="image" class="form-control image" type="file" accept="image/*" onchange="loadFile(event)">
                                <img class="img-responsive" id="output" width="200"/>
                                
                                <script>
                                    var loadFile = function(event) {
                                        var output = document.getElementById('output');
                                        output.src = URL.createObjectURL(event.target.files[0]);
                                    };
                                </script>
                            </div>
                        </div> 
                               
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary"> <span class="fa fa-plus-circle"></span> Registrar</button>
            </div>
                 
        </form>
        </div>
    </div>


@endsection

resources/views/productos/edit.blade.php
@extends('layouts.app')

@section('content')
    
<div class="container bg-info text-center shadow form-inline" style="padding: 10px;">
        <h1 class="text-center col-12">Administración de Productos</h1>
    </div>

    <div class="container pt-4 pb-4 bg-light shadow">
        <div class="card card-light text-dark">
            <h4 class="card-header titulo">
                <a class="btn btn-md btn-primary" href="{{route('producto.index')}}" ><span class="fa fa-arrow-left"></span></a>
                Modificar producto
            </h4>
            <form action="{{route('producto.update',$producto)}}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            @method('PUT')
            <div class="card-body">
                <div class="container">
                   
                        <div class="row">
                            <div class="form-group col">
                                <label for="umedida">Unidad de medida</label>
                                <select name="id_unidad_medida" id="unidad_medida" class="form-control">
                                    <option id="new_um">--AGREGAR NUEVO--</option>
                                    @foreach ($umedidas as $um)
                                    <option value="{{$um->id}}" @if ($um->unidad_medida == $producto->unidad_medida->unidad_medida) selected @endif>{{$um->unidad_medida}}</option>
                                    @endforeach
                                </select>
                            </div>
                                
                            <div class="form-group col">
                                <label for="marca">Marca</label>
                                <select name="id_marca" id="marca" class="form-control">
                                    <option id="new_marca">--AGREGAR NUEVO--</option>
                                    @foreach ($marcas as $m)
                                        <option value="{{$m->id}}" @if ($producto->marca->marca == $m->marca) selected  @endif>{{$m->marca}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                                
                        <div class="form-group">
                            <label for="marca">Descripcion corta</label>
                        <textarea name="descripcion" class="form-control" rows="3" maxlength="200" >{{$producto->descripcion}}</textarea>
                        </div>
            
                        <div class="form-group">
                            <label for="marca">Descripcion completa</label>
                            <textarea name="descripcion_completa" class="form-control" rows="3" maxlength="500">{{$producto->descripcion_completa}}</textarea>
                        </div>
            
                        <div class="row">
                            <div class="form-group col">
                                <label for="cod_manual">Código manual</label>
                                <input type="text" name="cod_manual" id="cod_manual" class="form-control" value="{{$producto->cod_manual}}">
                            </div>
                            
                            <div class="form-group col">
                                <label for="cod_bar">Código barras</label>
                                <input type="text" name="cod_bar" id="cod_bar" class="form-control" value="{{$producto->cod_bar}}">
                            </div>
                        </div>
            
                        <div class="row">
                            <div class="form-group col">
                                <label for="producto_servicio">Producto/Servicio</label>
                                <select class="form-control" name="producto_servicio">
                                    <option value="0" @if ($producto->producto_servicio == 0) selected @endif >Producto</option>
                                    <option value="1" @if ($producto->producto_servicio == 1) selected @endif >Servicio</option>
                                </select>
                            </div>
                            <div class="form-group col">
                                <label for="marca">Categoría</label>
                                <select name="id_categoria" id="marca" class="form-control">
                                <option id="new_marca">--AGREGAR NUEVO--</option>
                                @foreach ($categorias as $c)
                                    <option value="{{$c->id}}" @if ($producto->categoria->categoria == $c->categoria) selected @endif>{{$c->categoria}}</option>
                                @endforeach
                            </select>
                            </div>

                            <div class="form-group col">
                                <label for="tipo_iva">Tipo I.V.A.</label>
                                <select class="form-control" name="tipo_iva">
                                    <option value="10" @if ($producto->tipo_iva == '10%') selected @endif>10%</option>
                                    <option value="5"  @if ($producto->tipo_iva == '5%') selected @endif>5%</option>
                                    <option value="excenta"  @if ($producto->tipo_iva == 'excenta') selected @endif>EXCENTA</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <input name="activo" type="checkbox" aria-label="Activar/Desactiva producto" @if ($producto->activo == 'on') checked @endif >
                                    </div>
                                    <input type='text' class="form-control" readonly disabled value="Activar/Desactiva producto">
                            </div>
                            </div>
                            <div class="form-group col-6">
                                <div class="card">
                                    <div class="card-header">
                                            <label class="h6">Logotipo</label>
                                    </div>
                                    <div class="card-body">
                                        <img class="img-responsive" id="output" width="200" src="{{asset($imagen)}}"/> 
                                    </div>
                                    <div class="card-footer">
                                        <input name="image" class="form-control image" type="file" accept="image/*" onchange="loadFile(event)" value="{{$imagen}}">
                                        {{$imagen}}
                                    </div>
                                </div>
                                
                                <script>
                                    var loadFile = function(event) {
                                        var output = document.getElementById('output');
                                        output.src = URL.createObjectURL(event.target.files[0]);
                                    };
                                </script>
                            </div>
                        </div> 
                               
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" onclick="$('#confirm').removeClass('fa-check');$('#confirm').addClass('fa-spinner');$('#confirm').addClass('fa-spin');"> <span id="confirm" class="fa fa-check"></span> Confirmar</button>
            </div>
                 
        </form>
        </div>
    </div>
</script>
@endsection