routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@welcome')->name('welcome');   


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/ciudades/search', 'CiudadesController@search')->name('ciudades.search');

Route::resource('/comercio','ComercioController');
Route::resource('/usuario','UserController');
Route::resource('/usuario/preferencias','PreferenciasUsuarioController');
Route::resource('/producto','ProductosController');
Route::resource('/categoria','CategoriasController');
Route::resource('/marca','MarcasController');

Route::post('/getAllProducts','ProductosController@getAllProducts')->name('getAllProducts');
Route::post('/getAllCategories','CategoriasController@getAllCategories')->name('getAllCategories');
Route::post('/getAllMarcas','MarcasController@getAllMarcas')->name('getAllMarcas');

app/Comercio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Producto;
use App\Stock;
class Comercio extends Model
{
    protected $fillable = [
        'user_id', 'nombre', 'ruc', 'direccion', 'celular', 'departamento', 'ciudad', 'barrio','tipo_empresa','email','estado','activo','google_maps', 
    ];

    public function usuario(){
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function stock(){
        return $this->hasMany(Stock::class,'id','id_comercio');
    }
    public function rubros(){
        return $this->hasMany(ComercioRubro::class,'id','id_comercio');
    }
}

app/Http/Controllers/ComercioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Comercio;
use App\Departamento;
use App\Localidad;
use App\ComercioRubro;
use Auth;

use Illuminate\Support\Facades\DB;
class ComercioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(){
        $this->middleware('auth'); // Obliga inicio de sesión
    }
    public function index()
    {
        
        return view('comercio/index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departamentos = DB::table('departamentos')->orderBy('departamento', 'asc')->get();
        $localidades = DB::table('localidades')->orderBy('localidad', 'asc')->get();
        $rubros = DB::table('rubros')->orderBy('rubro', 'asc')->get();
    
        if(Auth::user()->comercio != null){
            return redirect('/home')->with('error','Ya tienes una empresa registrada!');
        }
        return view('comercio/create',['departamentos' => $departamentos,'rubros' => $rubros,'localidades' => $localidades]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		
    
        $c = new Comercio();
        $c->user_id = Auth::user()->id;
        $c->nombre = $request['nombre'];
        $c->ruc = $request['ruc'];
        $c->celular = $request['celular'];
        $c->departamento = $request['departamento'];
        $c->ciudad = $request['ciudad'];
        $c->barrio = $request['barrio'];
        $c->tipo_empresa = $request['tipo_empresa'];
        $c->save();

        foreach($request['rubros'] as $rubro){
            $cr = new ComercioRubro();
            $cr->id_comercio = $c->id;
            $cr->id_rubro = $rubro;
            $cr->save();
        }
        
        return redirect('/comercio/'.$c->id)->with('success', '¡Tu comercio ha sido registrado satisfactoriamente!');
    }   

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin_comercio = Comercio::find($id);
        if($admin_comercio != null){
            if(Auth::user()->comercio == $admin_comercio){   
                return view('comercio/show',['admin_comercio' => $admin_comercio]);
            }else{
                return redirect()->action('HomeController@index');
            }
        }else{
            return redirect()->action('HomeController@index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('comercio/edit');        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Comercio::find($id)->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(($comercio = Comercio::find($id) != null)){
            foreach ($comercio->rubros as $relacion_con_rubro) {
                $relacion_con_rubro->destroy();
            }
            foreach ($comercio->stock as $stock) {
                $stock->destroy();
            }
            
            $comercio->destroy();
    
        }
    }
}

resources/views/comercio/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container bg-light text-center shadow" style="padding: 10px;">
    <h1 style="color: rgb(104,105,106);">¡¡ANTES DE CONTINUAR ASEGÚRESE DE TENER LOS SIGUIENTES DATOS!!</h1>
</div>
<div class="row pt-4 pb-4 bg-info shadow">
    <div class="col">
        <div class="row" style="padding-left: 10px;padding-right: 10px;">
            <div class="col">
                <div class="container text-center"><i class="fa fa-address-card" style="font-size: 5em;color: white;"></i></div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container">
                    <h4 class="text-center text-light">Dirección comercial&nbsp;</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="row">
            <div class="col">
                <div class="container text-center"><i class="fa fa-phone"
                        style="font-size: 5em;color: white;"></i></div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container">
                    <h4 class="text-center text-light">Número de contacto</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="row">
            <div class="col">
                <div class="container text-center" style="color: white;"><i class="fa fa-id-card-o"
                        style="font-size: 5em;"></i></div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container">
                    <h4 class="text-center text-light">Detalles de identidad</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container  bg-light" style="padding: 50px;">
    <h4 style="color: rgb(150,5,5);">Completa los datos solicitados:</h4>
    <form method="POST" action="{{ route('comercio.store') }}">
        @csrf
        <div class="form-row">
            <div class="col">
                <div class="form-group"><label for="departamento">Departamento:</label>
                    <select id="depselect" class="form-control selectpicker" 
                        name="departamento"  data-live-search="true">
                        <optgroup label="Departamentos del Paraguay">
                            @if($departamentos != null)
                            <?php $ii = 0; ?>
                                @foreach ($departamentos as $d)
                                    <option value="{{$d->departamento}}" @if($ii == 0) selected @endif>{{$d->departamento}}</option>
                                <?php $ii = 1; ?>
                                @endforeach    
                            @endif

                        </optgroup>
                    </select></div>
            </div>
            <div class="col">
                <div class="form-group"><label for="ciudad">Ciudad:</label>
                    <select class="form-control selectpicker" id="select-country"  data-live-search="true" name="ciudad">
                        <optgroup label="Departamentos del Paraguay">
                                @if($localidades != null)
                                <?php $ii = 0;$ss = ""; ?>
                                    @foreach ($localidades as $l)
                                        <option data-tokens="{{strtolower($l->localidad)}}" value="{{$l->localidad}}" @if($ii == 0) selected @endif>{{$l->localidad}}</option>
                                    <?php $ii = 1; ?>
                                    @endforeach    
                                @endif
                        </optgroup>
                    </select>
                </div>
            </div>
            <div class="col">
                <div class="form-group"><label for="barrio">Barrio:</label><input required  class="form-control" type="text"
                        name="barrio"></div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-4">
                <div class="form-group"><label for="tipo_empresa">Tipo de empresa:</label><select class="form-control"
                        name="tipo_empresa">
                        <optgroup label="Seleccionar el tipo de su empresa">
                            <option value="Unipersonal" selected="">Unipersonal</option>
                            <option value="S.A." >S.A.</option>
                            <option value="S.R.L.">S.R.L.</option>
                            <option value="LTDA">LTDA</option>
                        </optgroup>
                    </select></div>
                <label for="nombre">Nombre de la empresa:</label><input required  name="nombre" class="form-control" type="text" placeholder="Ej: StoreExpress">
            </div>
            <div class="col">
                <h5>Rubros:</h5>
                <div class="form-row">
                    <div class="col" style="">
                            <select multiple="multiple" id="my-select" name="rubros[]" class="form-control">
                                @if($rubros != null)
                                <?php $ii = 0;$ss = ""; ?>
                                    @foreach ($rubros as $l)
                                        <option data-tokens="{{strtolower($l->rubro)}}" value="{{$l->id}}" @if($ii == 0) selected @endif>{{$l->rubro}}</option>
                                    <?php $ii = 1; ?>
                                    @endforeach    
                                @endif
                            </select>
                    </div>
                </div>
            </div>

            <div class="col">
                <h5>Logotipo:</h5>
                <div class="form-row">
                    <div class="col">
						<div class="form-group">
							<input class="form-control" type="file" accept="image/*" onchange="loadFile(event)" >
							<img class="img-responsive" id="output" style="width: 150px; height: 150px;"/>
							
							<script>
								var loadFile = function(event) {
									var output = document.getElementById('output');
									output.src = URL.createObjectURL(event.target.files[0]);
								};
							</script>
						</div>
					</div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
        <div class="col">
            <div class="form-group"><label>Celular:</label><input required  type="tel" name="celular" placeholder="Teléfono o celular" class="form-control"></div>
        </div>
        <div class="col">
            <div class="form-group"><label>R.U.C.:</label>
                <input required  type="text" class="form-control" name="ruc">
            </div>
        </div>
        <div class="col">
            <div class="form-check mb-2">
                <input required  class="form-check-input" type="checkbox" id="formCheck-1" name="terminos">
                <label class="form-check-label" for="formCheck-1">Acepto los términos y condiciones.</label>
            </div>
            <button class="btn btn-primary btn-block" type="submit">Registrar</button>
        </div>
    </div>
</form>
    
</div>

@endsection

resources/views/comercio/show.blade.php
@extends('layouts.app')
@section('content')

<div class="container bg-light text-center shadow" style="padding: 10px;">
    <h1 style="color: rgb(104,105,106);">PANEL DE ADMINISTRACIÓN - {{$admin_comercio->nombre}}</h1>

</div>
<div class="row pt-4 pb-4 bg-info shadow col-11 mx-auto">
    <div class="col ">
        <div class="row" style="padding-left: 10px;padding-right: 10px;">
            <div class="col">
                <div class="container text-center"><i class="fa fa-list" style="font-size: 5em;color: white;"></i></div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container">
                    <h4 class="text-center text-light">Inventario</h4>
                    <h4 class="text-center text-light">0</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="row">
            <div class="col">
                <div class="container text-center"><i class="fa fa-usd" style="font-size: 5em;color: white;"></i></div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container">
                    <h4 class="text-center text-light">Ventas</h4>
                    <h4 class="text-center text-light">$0</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="row">
            <div class="col">
                <div class="container text-center" style="color: white;"><i class="fa fa-truck"
                        style="font-size: 5em;"></i></div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container">
                    <h4 class="text-center text-light">Pedidos</h4>
                    <h4 class="text-center text-light">0</h4>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container  bg-light" style="padding: 50px;">

    <!-- Aviso de comercio no verificado -->
    @if($admin_comercio->estado == 'verificacion')
    <div class="alert alert-warning alert-dismissible fade show radius-0 border-dark" role="alert">
        En el proceso de verificación no es posible modificar ciertos datos de tu comercio. Si te haz equivocado contactar con <strong><a href="https://api.whatsapp.com/send?phone=595971308551&text=Modificacion%20de%20datos%20del%20comercio%20<?php echo str_replace('.','',str_replace(' ','%20',$admin_comercio->nombre)) ?>">Atención al Cliente</a></strong>.  

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif
    <!-- FIN Aviso de comercio no verificado -->

    <h3>Información general de {{$admin_comercio->nombre}}</h3>
    <hr>
    <div class="container">
        <form>
            <div class="form-row">
                <div class="col-8">
                    <div class="form-row">
                        <div class="col"><label>Nombre</label>
                            <div class="form-group"><input type="text"value="{{$admin_comercio->nombre}}" 
                                    class="form-control"  @if($admin_comercio->estado == 'verificacion')  name="nombre"  readonly @endif /></div>
                        </div>
                        <div class="col">
                            <div class="form-group"><label>R.U.C.</label><input type="text"
                                    value="{{$admin_comercio->ruc}}" class="form-control " @if($admin_comercio->estado == 'verificacion')  name="ruc" readonly @endif /></div>
                        </div>
                        <div class="col">
                            <div class="form-group"><label>Dirección</label><input type="text" name="direccion"
                                    value="{{$admin_comercio->direccion}}" class="form-control" /></div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <div class="form-group"><label>Tipo de Empresa</label><input type="text" name="tipo_empresa"
                                    value="{{$admin_comercio->tipo_empresa}}" class="form-control" /></div>
                        </div>
                        <div class="col">
                            <div class="form-group"><label>Celular/Teléfono</label><input type="text" name="celular"
                                    value="{{$admin_comercio->celular}}" class="form-control" /></div>
                        </div>
                        <div class="col">
                            <div class="form-group"><label>Correo electrónico</label><input type="text" name="email"
                                    value="{{$admin_comercio->email}}" class="form-control" /></div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col">
                            <div class="form-group"><label>Estado</label><input type="text"
                                    value="{{$admin_comercio->estado}}" class="form-control" readonly/></div>
                        </div>
                        <div class="col">
                            <div class="form-group"><label>Google Maps</label><input type="text" name="email"
                                    value="{{$admin_comercio->google_maps}}" class="form-control" /></div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label>Logotipo</label>
                        <input class="form-control" type="file" accept="image/*" onchange="loadFile(event)">
                        <img class="img-responsive" id="output" width="200"/>
                        
                        <script>
                            var loadFile = function(event) {
                                var output = document.getElementById('output');
                                output.src = URL.createObjectURL(event.target.files[0]);
                            };
                        </script>
                    </div>
                </div>
            </div>
            
            <div class="container">
                <div class="row">
                    
                </div>                  
            </div>
        </form>
    </div>


</div>

@endsection